/* Auto-generated by genmsg_cpp for file /home/mlab/ros/ic2020-read-only/ic2020_render/msg/rendupdate.msg */
#ifndef IC2020_RENDER_MESSAGE_RENDUPDATE_H
#define IC2020_RENDER_MESSAGE_RENDUPDATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ic2020_render
{
template <class ContainerAllocator>
struct rendupdate_ {
  typedef rendupdate_<ContainerAllocator> Type;

  rendupdate_()
  : numOfUpdates(0)
  , data()
  {
  }

  rendupdate_(const ContainerAllocator& _alloc)
  : numOfUpdates(0)
  , data(_alloc)
  {
  }

  typedef uint32_t _numOfUpdates_type;
  uint32_t numOfUpdates;

  typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  data;


  ROS_DEPRECATED uint32_t get_data_size() const { return (uint32_t)data.size(); }
  ROS_DEPRECATED void set_data_size(uint32_t size) { data.resize((size_t)size); }
  ROS_DEPRECATED void get_data_vec(std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other > & vec) const { vec = this->data; }
  ROS_DEPRECATED void set_data_vec(const std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other > & vec) { this->data = vec; }
private:
  static const char* __s_getDataType_() { return "ic2020_render/rendupdate"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "04c332cac37137a642a8f44f295c4870"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# Array of update structures\n\
uint32 numOfUpdates\n\
uint8[] data\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, numOfUpdates);
    ros::serialization::serialize(stream, data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, numOfUpdates);
    ros::serialization::deserialize(stream, data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(numOfUpdates);
    size += ros::serialization::serializationLength(data);
    return size;
  }

  typedef boost::shared_ptr< ::ic2020_render::rendupdate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ic2020_render::rendupdate_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct rendupdate
typedef  ::ic2020_render::rendupdate_<std::allocator<void> > rendupdate;

typedef boost::shared_ptr< ::ic2020_render::rendupdate> rendupdatePtr;
typedef boost::shared_ptr< ::ic2020_render::rendupdate const> rendupdateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ic2020_render::rendupdate_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ic2020_render::rendupdate_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ic2020_render

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ic2020_render::rendupdate_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ic2020_render::rendupdate_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ic2020_render::rendupdate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "04c332cac37137a642a8f44f295c4870";
  }

  static const char* value(const  ::ic2020_render::rendupdate_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x04c332cac37137a6ULL;
  static const uint64_t static_value2 = 0x42a8f44f295c4870ULL;
};

template<class ContainerAllocator>
struct DataType< ::ic2020_render::rendupdate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ic2020_render/rendupdate";
  }

  static const char* value(const  ::ic2020_render::rendupdate_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ic2020_render::rendupdate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Array of update structures\n\
uint32 numOfUpdates\n\
uint8[] data\n\
\n\
";
  }

  static const char* value(const  ::ic2020_render::rendupdate_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ic2020_render::rendupdate_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.numOfUpdates);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct rendupdate_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ic2020_render::rendupdate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ic2020_render::rendupdate_<ContainerAllocator> & v) 
  {
    s << indent << "numOfUpdates: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.numOfUpdates);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // IC2020_RENDER_MESSAGE_RENDUPDATE_H

