/* Auto-generated by genmsg_cpp for file /home/mlab/ros/ic2020-read-only/ic2020_toro/msg/loopnotice.msg */
#ifndef IC2020_TORO_MESSAGE_LOOPNOTICE_H
#define IC2020_TORO_MESSAGE_LOOPNOTICE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ic2020_toro
{
template <class ContainerAllocator>
struct loopnotice_ {
  typedef loopnotice_<ContainerAllocator> Type;

  loopnotice_()
  : close(0)
  {
  }

  loopnotice_(const ContainerAllocator& _alloc)
  : close(0)
  {
  }

  typedef uint8_t _close_type;
  uint8_t close;


private:
  static const char* __s_getDataType_() { return "ic2020_toro/loopnotice"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "3db2583c538d71b20052e0f0e775249f"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# char indicating we need to loop close\n\
uint8 close\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, close);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, close);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(close);
    return size;
  }

  typedef boost::shared_ptr< ::ic2020_toro::loopnotice_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ic2020_toro::loopnotice_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct loopnotice
typedef  ::ic2020_toro::loopnotice_<std::allocator<void> > loopnotice;

typedef boost::shared_ptr< ::ic2020_toro::loopnotice> loopnoticePtr;
typedef boost::shared_ptr< ::ic2020_toro::loopnotice const> loopnoticeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ic2020_toro::loopnotice_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ic2020_toro::loopnotice_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ic2020_toro

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ic2020_toro::loopnotice_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ic2020_toro::loopnotice_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ic2020_toro::loopnotice_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3db2583c538d71b20052e0f0e775249f";
  }

  static const char* value(const  ::ic2020_toro::loopnotice_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3db2583c538d71b2ULL;
  static const uint64_t static_value2 = 0x0052e0f0e775249fULL;
};

template<class ContainerAllocator>
struct DataType< ::ic2020_toro::loopnotice_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ic2020_toro/loopnotice";
  }

  static const char* value(const  ::ic2020_toro::loopnotice_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ic2020_toro::loopnotice_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# char indicating we need to loop close\n\
uint8 close\n\
\n\
";
  }

  static const char* value(const  ::ic2020_toro::loopnotice_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ic2020_toro::loopnotice_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ic2020_toro::loopnotice_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.close);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct loopnotice_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ic2020_toro::loopnotice_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ic2020_toro::loopnotice_<ContainerAllocator> & v) 
  {
    s << indent << "close: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.close);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IC2020_TORO_MESSAGE_LOOPNOTICE_H

