(cl:in-package ic2020_vodom-msg)
(cl:export '(KEYFRAME_NUM-VAL
          KEYFRAME_NUM
          ROTATION-VAL
          ROTATION
          TRANSLATION-VAL
          TRANSLATION
          HEIGHT-VAL
          HEIGHT
          WIDTH-VAL
          WIDTH
          IM-VAL
          IM
          NUMBEROF3DPOINTS-VAL
          NUMBEROF3DPOINTS
          POINT_STEP-VAL
          POINT_STEP
          POINTS-VAL
          POINTS
          NUMCORN1-VAL
          NUMCORN1
          CORN1-VAL
          CORN1
          STATUS-VAL
          STATUS
          NUMCORN2-VAL
          NUMCORN2
          CORN2-VAL
          CORN2
          NUMSURF-VAL
          NUMSURF
          FEATURES-VAL
          FEATURES
          DESCBUFFER-VAL
          DESCBUFFER
          SURFMATCHES-VAL
          SURFMATCHES
          IMUX-VAL
          IMUX
          IMUY-VAL
          IMUY
          IMUZ-VAL
          IMUZ
))